Use cursor signaling
gisce/oorq pull request #74
Opened 2018-03-19 07:30 UTC by ecarreras

Only enqueue jobs when the transaction is commited.

Needs https://github.com/gisce/erp/pull/6412

/cc @rchamorro

2018-04-09 15:15 UTC, ecarreras commented
Check autoworkers

2018-04-20 16:43 UTC, ecarreras commented
We have to inherit autoworkers and modify `work` method to register in memory and then when the transaction is committed the call the real `work`.

Then in all the modules that are using autoworkers we need to use the autoworker from oorq module

/cc @tinogis @guilleJB

2020-02-12 11:59 UTC, guilleJB requested changes
Little typo

2020-02-12 11:59 UTC, guilleJB commented on oorq/decorators.py
> +                    depends_on=current_job
```suggestion
                    depends_on=current_job,
```
Fix missing coma

2020-02-13 16:42 UTC, ecarreras commented
It seems exists a bug in RQ when using `enqueue_job()` dependencies aren't working...

2020-02-13 22:03 UTC, ecarreras commented
> It seems exists a bug in RQ when using `enqueue_job()` dependencies aren't working...

Tested with `test_oorq` module and method `test_dependency_job_on_commit()` and it works as expected enqueuing the job when the first job is finished

2020-02-21 08:49 UTC, merged