[FIX] Update code for rq new version, 1.0
gisce/oorq pull request #81
Opened 2019-04-08 08:30 UTC by destanyol

In the new version of rq, the function `get_failed_queue` has been deprecated.
This is a **non-tested update** of the code following the rq changelog of the v1.0 version.

2019-04-08 08:40 UTC, jaumef submitted a review, later dismissed

2019-04-08 08:40 UTC, jaumef commented on oorq/bin/requeue_failed.py
> +for job in pq.failed_job_registry:
```suggestion
for job in fq.failed_job_registry:
```

2019-04-08 08:41 UTC, guilleJB requested changes

2019-04-08 08:41 UTC, guilleJB commented on oorq/bin/requeue_failed.py
> +for job in pq.failed_job_registry:
`pq` is permantent queue not failed queue. Use `fq`

2019-04-08 08:49 UTC, jaumef commented
This PR must be on hold due to other requirements:

- rq-dashboard current version isn't compatible: `rq-dashboard 0.4.0 has requirement rq<1.0.0,>=0.3.8`
- redis<3.0 isn't compatible: `rq 1.0 has requirement redis>=3.0.0`

2019-09-25 09:06 UTC, ecarreras commented
I'm going to closes this because all is implemented in #83 Thanks for you work @destanyol

2019-09-25 09:06 UTC, closed without merging